
configfile: 'config.yaml'

#include: 'rules/gencode.rules'
include: 'rules/functional.rules'
include: 'rules/annotate.rules'
include: 'rules/tidy.rules'

# BATCH_KEY = pd.read_table(config['batches'], dtype=str)
# BATCHES = sorted(BATCH_KEY.batch.unique())
# BATCHES = ['Phase1']
# 
with open(config['chroms']) as clist:
    CHROMS = [c.strip() for c in clist.readlines()]
# 
# SOURCES = config['pesr_sources'] + ['depth']
# 
# wildcard_constraints:
#     source='(' + '|'.join(SOURCES) + ')',
#     chrom='(' + '|'.join(CHROMS) + ')'

SUBSETS = 'antisense lincRNA processed_transcript pseudogene'.split()
SUBSETS = 'protein_coding promoter functional antisense lincRNA processed_transcript pseudogene genic'.split()
# SUBSETS = 'protein_coding antisense lincRNA processed_transcript pseudogene'.split()

rule all:
    input:
        'annotations/SSC.combinations.txt',
