batches: ref/batch.key
groups: ref/quads.test.list
samples: ref/samples.test.list
idmap: ref/519families_idmapping
chroms: ref/chroms.test2.list

preprocess: True

blacklist: ref/b37.lumpy.exclude.4-13.bed.gz

ALL_SAMPLES: 'merged'

pesr_sources:
    - delly
    - lumpy
    - manta
    - wham
depth_sources:
    - cnmops
    - cnvnator
    - genomestrip

svtypes:
    - DEL
    - DUP
    - INV
    - BND

cnv_types:
    - DEL
    - DUP

pesr_alg_integration:
    vcfcluster:
        min_recip_frac: 0.1
        min_dist: 300
        min_svsize: 0
        blacklist: ref/b37.lumpy.exclude.4-13.bed.gz

pesr_cohort_integration:
    vcfcluster:
        min_recip_frac: 0.1
        min_dist: 300
        min_svsize: 0
        blacklist: ref/b37.lumpy.exclude.4-13.bed.gz

    
RdTest:
    gt_script: scripts/RdTest.R
    covfile: /data/talkowski/Samples/SFARI/deep_sv/asc_540/bincov/matrices/ASC540.all.binCov.raw.bed.gz
    medianfile: /data/talkowski/Samples/SFARI/deep_sv/asc_540/bincov/matrices/ASC540.all.binCov.median
    famfile: /data/talkowski/Samples/SFARI/lists/SFARI_Real.fam
    blacklist: /data/talkowski/Samples/SFARI/lists/SFARI.pilot.IDs.txt
