# Key
batch_key: ref/batch.key

# Input directories
input_vcfs: ../00_preprocessing/filtered_vcfs/
input_beds: ../00_preprocessing/std_beds/

# List of groups to integrate
groups: ref/families.list

# List of chromosomes to integrate
contigs: ref/contigs.fai

# Lists of algorithms to integrate
pesr_sources:
    - delly
    - lumpy
    - manta
    - wham
mei_sources:
    - melt
cnv_types:
    - DEL
    - DUP

# PE/SR clustering parameters
vcfcluster:
    dist: 300
    frac: 0.1
    blacklist: ref/b37.lumpy.exclude.4-13.bed.gz
    svsize: 0
    flags: ""
    #flags: "--preserve-ids"

# SV types to restrict VCF clustering to
svtypes:
    pesr: DEL,DUP,INV,BND
    mei: INS

# Depth clustering parameters
bedcluster:
    frac: 0.8
    flags: "--merge-coordinates"
