
configfile: 'config.yaml'

include: 'rules/pesr_integration.rules'
include: 'rules/depth_integration.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batch_key'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())

PESR_SOURCES = config['pesr_sources']
SOURCES = PESR_SOURCES + ['depth']
MEI_SOURCES = config['mei_sources'] + PESR_SOURCES
CNV = config['cnv_types']

with open(config['contigs']) as clist:
    CHROMS = [c.split()[0] for c in clist.readlines()]

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    svtype='(' + '|'.join(CNV) + ')',
    chrom='(' + '|'.join(CHROMS) + ')',
    batch='(' + '|'.join(BATCHES) + ')'

rule all:
    input:
        expand('rdtest_beds/{batch}.{source}.{chrom}.bed',
               batch=BATCHES, source=SOURCES, chrom=CHROMS),
        expand('vcfcluster/{batch}.{source}.{chrom}.vcf.gz',
               batch=BATCHES, source=SOURCES, chrom=CHROMS)
