batch_key: ref/batch.key
groups: ref/families.list

pesr_sources:
    - delly
    - manta
    # - lumpy
    # - wham
    # - melt
depth_sources:
    - cnmops
    - cnvnator

svtypes:
    - DEL
    - DUP
    - INV
    - BND

cnv_types:
    - DEL
    - DUP

# sources to remove outliers from 
outlier_removal: []
    # - delly
    # - manta
    # - lumpy
    # - wham 
