# Key
batch_key: ../../ref/batch.key
famfile: /data/talkowski/hw878/Prenatal/prenatal.fam

input_beds: ../../01_cohort_clustering/rdtest_beds
input_vcfs: ../../01_cohort_clustering/vcfcluster

sr_counts: '../../../pesr_testing/split_counts/cohort.txt.gz'

# Subsets to analyze
contigs: ../../ref/contigs.fai
pesr_sources:
    - delly
    - lumpy
    - manta
    - wham
    # - melt
