
configfile: 'config.yaml'

include: 'rules/filtered_integration.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batches'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())
BATCHES = ['Phase1']

with open(config['chroms']) as clist:
    CHROMS = [c.strip() for c in clist.readlines()]

SOURCES = config['pesr_sources'] + ['depth']

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    chrom='(' + '|'.join(CHROMS) + ')'

rule all:
    input:
        expand('vcfcluster/pesr_depth/{batch}.{chrom}.vcf.gz',
               batch=BATCHES, chrom=CHROMS)
