# Data subdirectory
workdir: combined_prob
rootdir: .

# Key
batches: ../ref/batch.key

# Subsets to analyze
# chroms: chroms.10.list
chroms: ref/chroms.autosomes.list
pesr_sources:
    - delly
    - lumpy
    - manta
    - wham

# Input from prior modules
input_vcfs: ../01_algorithm_integration/vcfcluster/
cnv_p: /data/talkowski/Samples/SFARI/DeepSeq/HarrisonCompare/GT_Filtering/clean_pipeline/combined_prob/combined_CNV.passing.p
bca_p: /data/talkowski/Samples/SFARI/DeepSeq/HarrisonCompare/GT_Filtering/clean_pipeline/combined_prob/combined_BCA.passing.p
# cnv_p: combined_CNV.passing.p
# bca_p: combined_BCA.passing.p

# PE/SR clustering parameters
vcfcluster:
    pesr:
        dist: 300
        frac: 0.1
        blacklist: ../ref/b37.lumpy.exclude.4-13.bed.gz
        svsize: 0
        svtypes: DEL,DUP,INV,BND
    pesr_depth:
        dist: 2000000
        frac: 0.8
        blacklist: ../ref/b37.lumpy.exclude.4-13.bed.gz
        svsize: 0
        svtypes: DEL,DUP,INV,BND
