# Key
batches: ../ref/batch.key

# Test stats directories
rdtest: "../rdtest/rdtest"
srtest: "../srtest/srtest"
petest: "../petest/petest"
baftest: "../baftest/baftest"
input_vcfs: "../algorithm_integration/vcfcluster"
input_beds: "../algorithm_integration/rdtest_beds"

# Subsets to analyze
groups: ../ref/quads.519.list
chroms: ../ref/chroms.all.list
pesr_sources:
    - delly
    - lumpy
    - manta
    - wham
