# Key
batch_key: ../../ref/batch.key

input_beds: ../../01_cohort_clustering/rdtest_beds
input_vcfs: ../../01_cohort_clustering/vcfcluster

# Subsets to analyze
contigs: ../../ref/contigs.fai
pesr_sources:
    - delly
    - lumpy
    - manta
    - wham

# RdTest parameters
rdtest: /PHShome/my520/code/RdTest/RdTest.R
coveragefile: /data/talkowski/xuefang/data/Prenatal/prenatal/metrics/bincov/Prenatal.bincov.gz
medianfile: /data/talkowski/xuefang/data/Prenatal/prenatal/metrics/bincov/Prenatal.bincov.median
famfile: /data/talkowski/hw878/Prenatal/prenatal.fam
variants_per_split: 100
