
configfile: 'config.yaml'


include: 'rules/rdtest.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batch_key'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())

PESR_SOURCES = config['pesr_sources']
SOURCES = PESR_SOURCES + ['depth']

with open(config['contigs']) as clist:
    CHROMS = [c.split()[0] for c in clist.readlines()]

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    chrom='(' + '|'.join(CHROMS) + ')'

rule all:
    input:
        expand('rdtest/{batch}.{source}.{chrom}.metrics',
               batch=BATCHES, source=SOURCES, chrom=CHROMS),
