
configfile: 'config.yaml'

include: 'rules/aggregate.rules'
include: 'rules/random_forest.rules'
include: 'rules/filter.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batches'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())
BATCHES = ['Pilot']

PESR_SOURCES = config['pesr_sources']
SOURCES = PESR_SOURCES + ['depth'] #+ ['depth', 'melt']
SOURCES = ['depth', 'melt']
SOURCES = ['melt']

with open(config['chroms']) as clist:
    CHROMS = [c.strip() for c in clist.readlines()]

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    chrom='(' + '|'.join(CHROMS) + ')'

rule all:
    input:
        # Aggregated tables
        expand('filtered_vcfs/{batch}.melt.{chrom}.vcf.gz',
               batch=BATCHES, chrom=CHROMS),
#        expand('metrics/{batch}.{source}.{chrom}.metrics',
#               batch=BATCHES, source=SOURCES, chrom=CHROMS),
        # Filtering (after RF)
#         expand('filtered_vcfs/{batch}.{source}.{chrom}.vcf.gz', 
#                batch=BATCHES, source=SOURCES, chrom=CHROMS),
#         expand('fails/{batch}.{source}.{chrom}.vcf.gz', 
#                batch=BATCHES, source=SOURCES, chrom=CHROMS),
        # De novo test stats
#         expand('dn_filtered_metrics/{batch}.{source}.{chrom}.metrics', 
#                batch=BATCHES, source=SOURCES, chrom=CHROMS)
#        expand('train_metrics/{batch}.metrics', batch=BATCHES),
#        expand('baf_metrics/{batch}.del.all.metrics', batch=BATCHES),
#        expand('baf_rf/{batch}.del.dep.txt', batch=BATCHES)
