
configfile: 'config.yaml'

include: 'rules/aggregate.rules'
include: 'rules/random_forest.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batches'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())

PESR_SOURCES = config['pesr_sources']
SOURCES = PESR_SOURCES + ['depth', 'melt']

with open(config['chroms']) as clist:
    CHROMS = [c.strip() for c in clist.readlines()]

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    chrom='(' + '|'.join(CHROMS) + ')'

rule all:
    input:
        expand('metrics/{batch}.{source}.{chrom}.metrics', batch=BATCHES, chrom=CHROMS, source=SOURCES),
#        expand('train_metrics/{batch}.metrics', batch=BATCHES),
#        expand('baf_metrics/{batch}.del.all.metrics', batch=BATCHES),
#        expand('baf_rf/{batch}.del.dep.txt', batch=BATCHES)
