
configfile: 'config.yaml'

include: 'rules/pesr_integration.rules'
include: 'rules/depth_integration.rules'

PESR_SOURCES = config['pesr_sources']
SOURCES = PESR_SOURCES + ['depth']
CNV = config['cnv_types']

with open(config['chroms']) as clist:
    CHROMS = [c.strip() for c in clist.readlines()]

wildcard_constraints:
    source='(' + '|'.join(SOURCES) + ')',
    svtype='(' + '|'.join(CNV) + ')',
    chrom='(' + '|'.join(CHROMS) + ')'

rule all:
    input:
        expand('pesr/rdtest_beds/{batch}.{source}.{chrom}.bed',
               batch=BATCHES, source=PESR_SOURCES, chrom=CHROMS),
        expand('depth/rdtest_beds/{batch}.depth.{chrom}.bed',
               batch=BATCHES, chrom=CHROMS),
